// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOPyTpYpc0QUHOMvzGFSL2deqf8J0rBJc',
    appId: '1:948643843856:web:623496f20e19ca701b1f95',
    messagingSenderId: '948643843856',
    projectId: 'toko-minuman',
    authDomain: 'toko-minuman.firebaseapp.com',
    storageBucket: 'toko-minuman.firebasestorage.app',
    measurementId: 'G-LLGGJNL6BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFqpX0Ezf_a08OakHmb61xk6jlN78XX8',
    appId: '1:948643843856:android:edfe6fa3f5cfc4991b1f95',
    messagingSenderId: '948643843856',
    projectId: 'toko-minuman',
    storageBucket: 'toko-minuman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NbJ9UchKM2BS6zkwWBoymFj6J3-4gHs',
    appId: '1:948643843856:ios:8c3c2fa9523d58291b1f95',
    messagingSenderId: '948643843856',
    projectId: 'toko-minuman',
    storageBucket: 'toko-minuman.firebasestorage.app',
    iosBundleId: 'com.example.tokoMinuman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NbJ9UchKM2BS6zkwWBoymFj6J3-4gHs',
    appId: '1:948643843856:ios:8c3c2fa9523d58291b1f95',
    messagingSenderId: '948643843856',
    projectId: 'toko-minuman',
    storageBucket: 'toko-minuman.firebasestorage.app',
    iosBundleId: 'com.example.tokoMinuman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOPyTpYpc0QUHOMvzGFSL2deqf8J0rBJc',
    appId: '1:948643843856:web:9ff53b85415a26101b1f95',
    messagingSenderId: '948643843856',
    projectId: 'toko-minuman',
    authDomain: 'toko-minuman.firebaseapp.com',
    storageBucket: 'toko-minuman.firebasestorage.app',
    measurementId: 'G-6XYKPM70VT',
  );
}
